version: '3.6'
services:
  rio-image-converter:
    build:
      context: .
      dockerfile: dockerfile-app
    ports:
    - "3030:3030"
    expose:
    - 3030
    restart: always
    volumes:
    - root-data:/app
volumes:
  root-data: 

