FROM node:13
WORKDIR . /app
RUN apt-get install make gcc g++ python tzdata
RUN cp /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime && echo "America/Sao_Paulo" >  /etc/timezone
COPY package.json ./
COPY . .
RUN npm install pm2 -g && npm install 
EXPOSE 3030
CMD ["pm2-runtime", "start", "pm2.json"]
